POST http://localhost:8081/customer/register
Content-Type: application/json 

{
    "cname":"HELi",
    "email":"hELI1@gmail.com",
    "pwd":"1234"
}

###
POST http://localhost:8081/customer/login
Content-Type: application/json 

{
    "email":"gunjal@gmail.com",
    "pwd":"1234"
}

###
POST http://localhost:8081/customerprofile/updatedetails/
Content-Type: application/json 

{
    "customerId":1,
    "cname":"gu",
    "DOB":"1997/12/12",
    "city": "jose",
    "stateId": 2,
    "countryId": 1,
    "nickname": "nickname"
}
###
POST http://localhost:3000/customerprofile/updatecontact/2
Content-Type: application/json 

{
    "email":"gunjal12@gmail.com",
    "mobileNo" : "1234567"
}

###
POST http://localhost:8081/restaurant/register
Content-Type: application/json 

{
    "rname":"gunjal",
    "email":"gunjal1gupta@gmail.com",
    "pwd":"1234"
}

###
POST http://localhost:8081/restaurant/login
Content-Type: application/json 

{
    "email":"gunjalgupta@gmail.com",
    "pwd":"1234"
}

###



POST http://localhost:8081/restaurant/updatedetails/
Content-Type: application/json 

{
    "restaurantId": 1,
    "email" : "gunjal1gupta@gmail.com",
    "rname":"gunjal",
    "city": "jose",
    "stateId": 3,
    "countryId":"1"
}
###
POST http://localhost:3000/restaurant/updatecontact/3
Content-Type: application/json 

{
    "email":"gunjal12@gmail.com",
    "mobileNo" : "1234567"
}
###
POST http://localhost:8081/restaurant/adddish
Content-Type: application/json 

{
    "dname" :"fries",
    "ingredients" : "Lime, spices",
    "ddesc" : "",
    "restaurantId" : 1,
    "cuisineId" : 2,
    "veg" : true,
    "nonVeg" : false,
    "vegan" : true,
    "categoryId" : 5,
    "price" : 5
}
###
POST http://localhost:8081/restaurant/editdish/18
Content-Type: application/json 

{
    "values":
{
    "dname" : "Paneer tikka",
    "ingredients" : "Cottage cheese",
    "ddesc" : "'Barceque the marinated paneer'",
    "restaurantId" : 1,
    "cuisineId" : 1,
    "veg" : true,
    "nonVeg" : false,
    "vegan" : true,
    "categoryId" : 1,
    "price" : 10
}
}
###
POST  http://localhost:8081/restaurant/getdish/5

###

POST  http://localhost:8081/restaurant/profile/5
Content-Type: application/json 

{
    "restaurantId":55
}
###
GET  http://localhost:8081/customerprofile/2
Content-Type: application/json 

{
    "customerId":2
}
###
GET   http://localhost:8081/customerprofile/getRestaurants/5


###
POST  http://localhost:8081/customerprofile/searchRestaurant
Content-Type: application/json 

{
    "name":""
}

###
POST  http://localhost:8081/restaurant/profile/1
###
POST http://localhost:8081/restaurant/deletedish/11
###

POST  http://localhost:8081/restaurant/getd/12

###
POST  http://localhost:8081/order/addorder
Content-Type: application/json 

{
    "resId":1,
    "cusId": 5,
    "ostatus":"placed",
    "total":30,
    "invoiceId":"sfv"
}
###
POST  http://localhost:8081/order/adddetails
Content-Type: application/x-www-form-urlencoded  


    [
{
    "invoiceId":"sfv",
    "dishId": 13,
    "quantity":3,
    "price":3,
    "total":9
},
{
    "invoiceId":"sfv",
    "dishId": 14,
    "quantity":5,
    "price":5,
    "total":25
},
{
    "invoiceId":1,
    "dishId": 12,
    "quantity":5,
    "price":3,
    "total":15
}
    ]
###
POST  http://localhost:8081/customer/showfav/5
Content-Type: application/json 

{
    "restaurantId":2,
    "customerId": 5  
}
###
POST  http://localhost:8081/customer/checkfav
Content-Type: application/json 

{
    "restaurantId":6,
    "customerId": 5  
}
###
POST http://localhost:8081/order/getcusdetail
Content-Type: application/json 

{
    "customerId": 5  
}

###
POST http://localhost:8081/customer/fetchaddress/5
Content-Type: application/json 

{
    "customerId": 5  
}

###
POST http://localhost:8081/customer/addaddress
Content-Type: application/json 

{
    "customerId": 5,  
    "addline1": "The alameda",
    "addline2": "near diridon station",
    "city": "san jose",
    "state": "CA",
    "zipcode": 95126
}